export const AppRoutes = {
    MAIN: '/',
    CONSULT: '/consult',
    USERS: '/users',
    INFO: '/info',
    Dimasichock: '/dimasichock',
    YARYNA: '/yara',
    Andriy:'/andriy',
    YEVHEN: '/yevhen',
    LOGIN: '/login',
    // ADMIN: '/admin',
    USER: '/user/:userId',
    MYLOGIN: '/yara/welcome',
    NOTMYLOGIN: '/yara/guest',
    VIEW: '/yara/view',
    ANDRIYLOGIN:'/andriy/login',
    GUESTLOGIN:'/andriy/guest',
    MENTOR: '/mentor',
    MENTOR_HOC: '/mentor/hoc',
    OREST: '/orest',
    ADMIN: '/dimasichock/admin',
    FAKESTUDENT: '/dimasichock/fake',
    STUDENT: '/dimasichock/student',
    OUSER: '/orest/ouser',
    OADMIN: '/orest/oadmin',
    WRONGSITE: '/orest/ooops'
}
